#!/usr/bin/env bash

NOTES_DIR="$HOME/Documents/notes"
echo "Notes directory: $NOTES_DIR"

notes_index() {
    # echo which shell is running
    local dir="$1"
    base_name="$(basename "$dir")"
    local index_file="${dir}/${base_name}-index.md"
    echo "Index file: $index_file"
    local title="$(basename "$dir" | sed 's/-index//')"
    echo "dir: $dir"
    local navigation_ribbon=''
    temp_dir="$dir"
    while [[ ! "$temp_dir" == "$NOTES_DIR" ]]; do
        local parent_dir="$(dirname "$temp_dir")"
        local parent_name="$(basename "$parent_dir")"
        echo "parent_name: $parent_name"
        echo "parent_dir: $parent_dir"
        navigation_ribbon="[$parent_name]($parent_name/$parent_name-index.md) > $navigation_ribbon"
        temp_dir="$parent_dir"
    done
    navigation_ribbon="${navigation_ribbon}[$title]($HTML_DIR/$base_name-index.md)"
    echo 'navigation_ribbon: ' $navigation_ribbon

    echo "# ${title^}" > "$index_file"

    for sub in "$dir"/*; do
        if [[ -d "$sub" ]]; then
            local subname="$(basename "$sub")"
            local subindex="${subname}/${subname}-index.md"
            echo "## [${subname^}]($subindex)" >> "$index_file"
            notes_index "$sub"
        elif [[ "$sub" == *.md && ! "$sub" == *"-index.md" ]]; then
            local filename="$(basename "$sub" .md)"
            echo "## [${filename^}]($filename.md)" >> "$index_file"
        fi
    done
    # echo "${navigation_ribbon}" >> "$index_file"
}

if [[ "$1" == "--help" || "$1" == "-h" ]]; then
    echo "Usage:"
    echo "notes -> open notes directory"
    echo "notes name -> create new note if it doesn't exist, open notes directory"
    echo "note --help -> show this help message"
elif [[ -z "$1" ]]; then
    notes_index $NOTES_DIR
    code -n --profile notes $NOTES_DIR
elif [[ "$1" == "view" ]]; then
    notes_index $NOTES_DIR
    code -n --profile notes $NOTES_DIR/notes-index.md
elif [[ "$1" == "clean" ]]; then
    find $NOTES_DIR -type f -name "*-index.md" -delete
elif [[ "$1" == "index" ]]; then
    notes_index $NOTES_DIR
fi