#!/bin/bash

wait_for_status() {
    local target_status="$1"  # The desired status: "connected" or "disconnected"
    local previous_status=""

    while true; do
        current_status=$(networksetup -showpppoestatus "VPN")
        if [ "$current_status" != "$previous_status" ]; then
            echo "$current_status"
            previous_status="$current_status"
        fi

        if [ "$current_status" = "$target_status" ]; then
            break
        fi

        sleep 2
    done
}

connect_vpn() {
    networksetup -connectpppoeservice "VPN"
    wait_for_status "connected"
}

disconnect_vpn() {
    networksetup -disconnectpppoeservice "VPN"
    wait_for_status "disconnected"
}

if [ "$1" = "-d" ]; then
    disconnect_vpn
else
    connect_vpn
fi
